- name: Stop Node2 and Node3 App
  command: rabbitmqctl stop_app
  when: inventory_hostname in ['node2', 'node3']

- name: Reset Node2 and Node3 App
  command: rabbitmqctl reset
  when: inventory_hostname in ['node2', 'node3']

- name: Join Node1 Cluster
  command: rabbitmqctl join_cluster rabbit@node1
  when: inventory_hostname in ['node2', 'node3']

- name: Start Node2 and Node3 App
  command: rabbitmqctl start_app
  when: inventory_hostname in ['node2', 'node3']